<a href="https://colab.research.google.com/github/mohdsaadoon/DL_Projects/blob/main/Perceptron_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perceptron from scratch

We will be reimplementing a Neural Networks from scratch.We are going to build a simple Perceptron on a small dataset that contains only 3 features.

<img src='https://miro.medium.com/v2/resize:fit:1024/0*RRhMRYvyPr71WhJ-.jpg' width="500" height="250">



Note: In this notebook we only used Numpy and Pandas packages for the implemention of Perceptron.

# 1. Import Required Packages

[1.1] We are going to use numpy and random packages

In [33]:
# import the necessary packages
import numpy as np
import pandas as pd
import random

# 2. Define Dataset

[2.1] We are going to use a simple dataset containing 3 features and 7 observations. The target variable is a binary outcome (either 0 or 1)

In [34]:
# define a simple array that containing 3 features and 7 obs.

input_set = np.array([[0,1,0], [0,0,1], [1,0,0], [1,1,0], [1,1,1], [0,1,1], [0,1,0]])
labels = np.array([[1], [0], [0], [1], [1], [0], [1]])


# 3. Set Initial Parameters

[3.1] Let's set the seed in order to have reproducible outcomes

In [35]:
#set seed 42
np.random.seed(42)


[3.2] Define a function that will create a Numpy array of a given shape with random values.


For example, `initialise_array(3,1)` will return an array of dimensions (3,1)that can look like this (values may be different):


`array([[0.37454012],
       [0.95071431],
       [0.73199394]])`

In [36]:
#funcation that returen shape with a random values
def initialise_array(n_features,n_observations):
    shape = np.random.rand(n_features,n_observations)

    return shape

In [37]:
#example of the returning function
initialise_array(3,1)

array([[0.37454012],
       [0.95071431],
       [0.73199394]])

[3.3]Create a Numpy array of shape (3,1) called `init_weights` filled with random values and print them.

In [38]:
#array return random values and assgin it to init_weights var
init_weights = np.random.rand(3,1)
print(init_weights)

[[0.59865848]
 [0.15601864]
 [0.15599452]]


[3.4] Create a Numpy array of shape (1,) called `init_bias` filled with a random value and print it.

In [39]:
#array return random values and assgin it to init_bias var
init_bias = np.random.rand(1,)
print(init_bias)

[0.05808361]


[3.5] Assert statements to check your created variables have the expected shapes

In [40]:
assert init_weights.shape == (3, 1)
assert init_bias.shape == (1,)

# 4. Define Linear Function
In this section we are going to implement the linear function of a neuron:



[4.1]: Define a function that will perform a dot product on the provided X and weights and add the bias to it

In [41]:
def linear(X, weights, bias):
   return np.dot(X , weights) + bias



[4.2] Assert statements to check your linear function is behaving as expected

In [42]:
test_weights = [[0.37454012],[0.95071431],[0.73199394]]
test_bias = [0.59865848]
assert linear(X=input_set[0], weights=test_weights, bias=test_bias)[0] == 1.54937279
assert linear(X=input_set[1], weights=test_weights, bias=test_bias)[0] == 1.3306524199999998
assert linear(X=input_set[2], weights=test_weights, bias=test_bias)[0] == 0.9731985999999999
assert linear(X=input_set[3], weights=test_weights, bias=test_bias)[0] == 1.9239129099999999
assert linear(X=input_set[4], weights=test_weights, bias=test_bias)[0] == 2.65590685
assert linear(X=input_set[5], weights=test_weights, bias=test_bias)[0] == 2.28136673
assert linear(X=input_set[6], weights=test_weights, bias=test_bias)[0] == 1.54937279

# 5. Activation Function

In the forward pass, an activation function is applied on the result of the linear function. We are going to implement the sigmoid function and its derivative:



[5.1]: Define a function that will implement the sigmoid function

In [43]:
#Activation Function and it’s derivative: Our activation function is the sigmoid function.
def sigmoid(x):

    return 1/ (1+np.exp(-x))

[5.2] Assert statements to check your sigmoid function is behaving as expected

In [44]:
assert sigmoid(0) == 0.5
assert sigmoid(1) == 0.7310585786300049
assert sigmoid(-1) == 0.2689414213699951
assert sigmoid(9999999999999) == 1.0
assert sigmoid(-9999999999999) == 0.0

<ipython-input-43-830c95932d80>:4: RuntimeWarning: overflow encountered in exp
  return 1/ (1+np.exp(-x))


[5.3]: Define a function that will implement the derivative of the sigmoid function

In [45]:
#Function that calculates the derivative of the sigmoid function.
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

[5.2] Assert statements to check your sigmoid_derivative function is behaving as expected

In [46]:
assert sigmoid_derivative(0) == 0.25
assert sigmoid_derivative(1) == 0.19661193324148185
assert sigmoid_derivative(-1) == 0.19661193324148185
assert sigmoid_derivative(9999999999999) == 0.0
assert sigmoid_derivative(-9999999999999) == 0.0

<ipython-input-43-830c95932d80>:4: RuntimeWarning: overflow encountered in exp
  return 1/ (1+np.exp(-x))


# 6. Forward Pass

Now we have everything we need to implement the forward propagation

[6.1]: Define a function that will implement the forward pass (apply linear function on the input followed by the sigmoid activation function)

In [47]:
#defain funcation that will implement forward pass
def forward(X, weights, bias):
    return sigmoid(np.dot(X, weights) + bias)


[6.2] Assert statements to check your forward function is behaving as expected

In [48]:
assert forward(X=input_set[0], weights=test_weights, bias=test_bias)[0] == 0.8248231247647452
assert forward(X=input_set[1], weights=test_weights, bias=test_bias)[0] == 0.7909485322272701
assert forward(X=input_set[2], weights=test_weights, bias=test_bias)[0] == 0.7257565873271445
assert forward(X=input_set[3], weights=test_weights, bias=test_bias)[0] == 0.8725741389540382
assert forward(X=input_set[4], weights=test_weights, bias=test_bias)[0] == 0.9343741240208852
assert forward(X=input_set[5], weights=test_weights, bias=test_bias)[0] == 0.9073220375080315
assert forward(X=input_set[6], weights=test_weights, bias=test_bias)[0] == 0.8248231247647452

# 7. Calculate Error

After the forward pass, the Neural Networks will calculate the error between its predictions (output of forward pass) and the actual targets.

[7.1]: Define a function that will implement the error calculation (difference between predictions and actual targets)

In [49]:
#calculate the differ between the actual and target
def calculate_error(actual, pred):
    error = pred - actual
    return error.sum()

[7.2] Assert statements to check your calculate_error function is behaving as expected

In [50]:
test_actual = np.array([0,0,0,1,1,1])
assert calculate_error(actual=test_actual, pred=[0,0,0,1,1,1]).sum() == 0
assert calculate_error(actual=test_actual, pred=[0,0,0,1,1,0]).sum() == -1
assert calculate_error(actual=test_actual, pred=[0,0,0,0,0,0]).sum() == -3

# 8. Calculate Gradients
Once the error has been calculated, a Neural Networks will use this information to update its weights accordingly.

[8.1] Let's creata function that calculate the gradients using the sigmoid derivative function and applying the chain rule.

In [51]:

def calculate_gradients(pred, error, input):
  dpred = sigmoid_derivative(pred)
  z_del = error * dpred
  gradients = np.dot(input.T, z_del)
  return gradients, z_del

# 9. Training

Now that we built all the components of a Neural Networks, we can finally train it on our dataset.

[9.1] Create 2 variables called `weights` and `bias` that will respectively take the value of `init_weights` and `init_bias`

In [52]:
weights = init_weights
bias = init_bias

[9.2] Create a variable called `lr` that will be used as the learning rate for updating the weights

In [53]:
lr = 0.5

[9.3] Create a variable called `epochs` with the value 10000. This will the number of times the Neural Networks will process the entire dataset and update its weights

In [54]:
epochs = 10000

[9.4] Create a for loop that will perform the training of our Neural Networks

In [55]:
for epoch in range(epochs):
    inputs = input_set

    # Forward Propagation
    z = forward(X=inputs, weights=weights, bias=bias)

    # Error
    error = calculate_error(actual=labels, pred=z)

    # Back Propagation
    gradients, z_del = calculate_gradients(pred=z, error=error, input=input_set)

    # Update parameters
    weights = weights - lr * gradients
    for num in z_del:
        bias = bias - lr * num


[9.5]Print the final values of `weights` and `bias`

In [56]:
print(weights)
print(bias)

[[ 0.99021769]
 [ 2.19115559]
 [-0.27866997]]
[-1.57419278]


# 10. Compare before and after training

Let's compare the predictions of our Neural Networks before (using `init_weights` and `init_bias`) and after the training (using `weights` and `bias`)

[10.1] Create a function to display the values of a single observation from the dataset (using its index), the error and the actual target and prediction

In [57]:
def compare_pred(weights, bias, index, X, y):
    pred = forward(X=X[index], weights=weights, bias=bias)
    actual = y[index]
    error = calculate_error(actual, pred)
    print(f"{X[index]} - Error {error} - Actual: {actual} - Pred: {pred}")

[10.2] Compare the results on the first observation (index 0)

In [58]:
compare_pred(weights=init_weights, bias=init_bias, index=0, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=0, X=input_set, y=labels)

[0 1 0] - Error -0.44667797055005865 - Actual: [1] - Pred: [0.55332203]
[0 1 0] - Error -0.35047252851175725 - Actual: [1] - Pred: [0.64952747]


[10.3] Compare the results on the second observation (index 1)

In [59]:
compare_pred(weights=init_weights, bias=init_bias, index=1, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=1, X=input_set, y=labels)

[0 0 1] - Error 0.5533160679949385 - Actual: [0] - Pred: [0.55331607]
[0 0 1] - Error 0.1355371274402587 - Actual: [0] - Pred: [0.13553713]


[10.4] Compare the results on the third observation (index 2)

In [60]:
compare_pred(weights=init_weights, bias=init_bias, index=2, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=2, X=input_set, y=labels)

[1 0 0] - Error 0.6585281663218256 - Actual: [0] - Pred: [0.65852817]
[1 0 0] - Error 0.35801843913131365 - Actual: [0] - Pred: [0.35801844]


[10.5] Compare the results on the forth observation (index 3)

In [61]:
compare_pred(weights=init_weights, bias=init_bias, index=3, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=3, X=input_set, y=labels)

[1 1 0] - Error -0.30730251163799815 - Actual: [1] - Pred: [0.69269749]
[1 1 0] - Error -0.16698043290039477 - Actual: [1] - Pred: [0.83301957]


[10.6] Compare the results on the fifth observation (index 4)

In [62]:
compare_pred(weights=init_weights, bias=init_bias, index=4, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=4, X=input_set, y=labels)

[1 1 1] - Error -0.27512867537455343 - Actual: [1] - Pred: [0.72487132]
[1 1 1] - Error -0.2094058490246128 - Actual: [1] - Pred: [0.79059415]


[10.7] Compare the results on the sixth observation (index 5)

In [63]:
compare_pred(weights=init_weights, bias=init_bias, index=5, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=5, X=input_set, y=labels)

[0 1 1] - Error 0.5914823619815118 - Actual: [0] - Pred: [0.59148236]
[0 1 1] - Error 0.5837757723770758 - Actual: [0] - Pred: [0.58377577]


[10.8] Compare the results on the sixth observation (index 5)

In [64]:
compare_pred(weights=init_weights, bias=init_bias, index=6, X=input_set, y=labels)
compare_pred(weights=weights, bias=bias, index=6, X=input_set, y=labels)

[0 1 0] - Error -0.44667797055005865 - Actual: [1] - Pred: [0.55332203]
[0 1 0] - Error -0.35047252851175725 - Actual: [1] - Pred: [0.64952747]


We can see after 10000 epochs, our Neural Networks is performing extremely well on our dataset. It has found pretty good values for the weights and bias to make accurate prediction.